ci: pin Meson on fedora/debian docker images to 1.5.2 for now
Fixes g-ir-scanner breakage that seems to happen with latest Meson 1.6.0.

/usr/bin/ld: build/tmp-introspectki7q5vp9/GstBase-1.0.o: undefined reference to symbol 'gst_init'
/usr/bin/ld: build/subprojects/gstreamer/gst/libgstreamer-1.0.so.0: error adding symbols: DSO missing from command line

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7753>